### ISSUE TITLE
Strange results obtained for a case study

### ISSUE THREAD

**Issue by dguijo** [hfawaz/cd-diagram#1]
Hi Hassan,
First of all, thank you for sharing the code. 

I've run your code using several combinations of results, for all of them, I obtained interpretable diagrams except for one (I attach the results csv used - see the compressed file). 

The thing is that it doesn't make sense, since the clf3 is a way better than the rest of the classifier.

Thank you again for your work.

Best, 
David.

![cd-diagram](https://user-images.githubusercontent.com/47889499/69010546-bb28b280-0958-11ea-9f95-94f13214bc7b.png)

[example.zip](https://github.com/hfawaz/cd-diagram/files/3855825/example.zip)

**Comment by hfawaz** [comment]
Hi David, 

Thanks for this. 

I think this comes from using the Wilcoxon Signed Rank Test to compute the pairwise significance which does not necessarily follow the average ranking of classifiers. 

You can see in [this paper](https://ueaeprints.uea.ac.uk/65985/1/Accepted_manuscript.pdf) section 5.1 ("HESCA Accuracies on TestData") how this could occur in such cd diagram. 

Let me know if you have more questions,

Best, 
Hassan

**Comment by dguijo** [comment]
Hi again, 
Thank you for your quick answer. It can happens when the Wilconxon Signed Rank Test is used.

I close the issue.
