### ISSUE TITLE
Bonferroni-Dunn post-hoc test

### ISSUE THREAD

**Issue by jayahm** [hfawaz/cd-diagram#2]
Is this library can also be used for Bonferroni–Dunn post-hoc test?

**Comment by hfawaz** [comment]
For now it supports only the Wilcoxon Signed Rank test with Holm's alpha correction.

**Comment by hfawaz** [comment]
I think you can find the implementation here: 

https://docs.biolab.si//3/data-mining-library/reference/evaluation.cd.html#cd-diagram

**Comment by jayahm** [comment]
Thanks!
